modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"

[[mixins]]
config = "brewery-common.mixins.json"

[[mods]]
modId = "brewery"
version = "${version}"
displayName = "[Let's Do] Brewery"
authors = "satisfy"
credits = "MissLilitu, CR-055"
description = '''
Foaming mugs, copper kettles and the smell of fresh pretzels. Brew your own beer, cook hearty food and throw an Oktoberfest to remember.'''
logoFile = "pack.png"
displayURL = "https://www.lets-do.ch"

[[dependencies.brewery]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.brewery]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.brewery]]
modId = "farm_and_charm"
type = "required"
versionRange = "[1.1.27,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.brewery]]
modId = "foundation"
type = "required"
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"
